### PR TITLE
Spending guidelines

### PR DESCRIPTION
**Pull request by davidtavarez**
This is simple document defining some basic spending guidelines. This document can be expanded in the future. Rendered file here: https://github.com/davidtavarez/docs/blob/grincc-spending-guidelines/spending-guidelines.md

### CODE REVIEW

**Review by MCM-Mike — COMMENTED** [review]
Changes looking good and I can relate to these rules.

**Review by MCM-Mike — APPROVED** [review]
I am fine with these rules.

**Comment by Anynomouss** [comment]
See textual changes I made, Approved after implementing these textual changes.

**Review by Anynomouss — APPROVED** [review]
Great, I agree with these guidelines.

**Pull request merged**
